# name: API Tests

# on:
#   push:
#     branches:
#       - dihan

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
          
#       - name: Run API Tests
#         id: run-newman
#         uses: anthonyvscode/newman-action@v1
#         with:
#           collection: collection.json
#           reporters: cli
          
#       - name: Output summary to console
#         run: echo ${{ steps.run-newman.outputs.summary }}